### ISSUE TITLE
Chest Commands Converter.

### ISSUE THREAD

**Issue by TheIntelloBox** [SuperRonanCraft/AdvancedCustomMenu#17]
**Suggestion** (How it may be resolved):

Chest Commands Converter : /acm convert, and it will convert the chest commands files to the Advanced Custom Menu files. :D

**Comment by SuperRonanCraft** [comment]
Very difficult to implement, as that could be another plugin entirely, the file formats are super dynamic on chestcommands in terms int he amount of ways a menu can be formatted, in this plugin, there's only one way each part can connect and that is to simplify the menu creation experience and have subtle changes in code rather than trying to allow all types of formats work. In other words, rather have someone who loves this plugin and have them create a new plugin for the conversion tool.
